version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - 8080:80
      - 9443:443
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  app:
    build:
     context: ./app
     dockerfile: Dockerfile
    restart: always
    container_name: app
    ports:
      - 8080:8080
    working_dir: /app
    env_file:
     - ./app/.env
    volumes:
      - ./app:/app

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
  
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events_api

  mongo:
    image: mongo:3.7
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: events_api
    ports:
      - 27018:27017
