server:
  port: ${SERVER_PORT:8080}
spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: POSTGRESQL
    show-sql: false
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:redis}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:events_api}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:postgres}
    driverClassName: org.postgresql.Driver
    validationQuery: SELECT 1
    testWhileIdle: true
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:root}:${MONGODB_PASS:root}@${MONGODB_HOST:mongodb}:${MONGODB_PORT:27017}/?authSource=admin
      database: ${MONGODB_DATABASE:events_api}